# Generated by Django 3.1.7 on 2021-07-04 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pizzaapp', '0002_customermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=10)),
                ('phoneno', models.CharField(max_length=10)),
                ('address', models.CharField(max_length=50)),
                ('orderitems', models.CharField(max_length=10)),
            ],
        ),
    ]
